// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission06.Models;

namespace Mission06.Migrations
{
    [DbContext(typeof(MovieEntryContext))]
    [Migration("20230214041700_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("Mission06.Models.MovieEntry", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieId");

                    b.ToTable("entries");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            Category = "Comedy",
                            Director = "Peter Segal",
                            Edited = false,
                            LentTo = "Johnny",
                            Notes = "This is Johnny's all-time favorite movie",
                            Rating = "PG-13",
                            Title = "Tommyboy",
                            Year = 1995
                        },
                        new
                        {
                            MovieId = 2,
                            Category = "Romance/Fantasy",
                            Director = "Richard Curtis",
                            Edited = false,
                            LentTo = "Johnny",
                            Notes = "This movie has the best message of any movie ever",
                            Rating = "R",
                            Title = "About Time",
                            Year = 2013
                        },
                        new
                        {
                            MovieId = 3,
                            Category = "Fantasy/Adventure",
                            Director = "Peter Jackson",
                            Edited = false,
                            LentTo = "Johnny",
                            Notes = "Favorite of all the movies, but the whole trilogy is the best of all time.",
                            Rating = "PG-13",
                            Title = "Lord of the Rings: Return of the King",
                            Year = 2003
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
